name: Motore di Scouting (Playwright)

on:
  workflow_dispatch: 
  schedule:
    - cron: '0 3 * * 1,4' 

jobs:
  scout-immobili:
    runs-on: ubuntu-latest
    steps:
      - name: Scarica il codice del repository
        uses: actions/checkout@main # Aggiornato per bypassare Node 20

      - name: Installa Python
        uses: actions/setup-python@main # Aggiornato per bypassare Node 20
        with:
          python-version: '3.11'

      - name: Installa dipendenze
        run: |
          python -m pip install --upgrade pip
          pip install pandas playwright
          playwright install chromium

      - name: Esegui Scraper
        run: python scraper.py

      - name: Salva il nuovo Database su GitHub
        run: |
          git config --global user.name "GECO Scraper Bot"
          git config --global user.email "bot@geco.local"
          if [ -f annunci_padova.csv ]; then
            git add annunci_padova.csv
            git commit -m "Aggiornamento Database Immobili Padova" || echo "Nessun nuovo dato da salvare"
            git push
          else
            echo "Nessun file CSV generato. Lo scraper è stato probabilmente bloccato."
          fi
